apiVersion: apps/v1
kind: Deployment
metadata:
  name: aksara-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aksara-app
  template:
    metadata:
      labels:
        app: aksara-app
    spec:
      containers:
      - name: aksara-app
        image: raid/aksara-monolith:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 14022
        livenessProbe:
          httpGet:
            path: /
            port: 14022
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: aksara-app
spec:
  selector:
    app: aksara-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 14022
      nodePort: 30080
  type: NodePort
